### ISSUE TITLE
Support WebhookChannel2023

### ISSUE THREAD

**Issue by elf-pavlik** [woutslabbinck/Solid-Notification#4]
I PRd some Webhook code to https://github.com/o-development/solid-notification-client/pull/1

I think we should talk together with @jaxoncreed about coordinating if not joining efforts!

**Comment by woutslabbinck** [comment]
That sounds like a good idea!

**Comment by jaxoncreed** [comment]
Sure, send an invite over. I'm available anytime on Tuesday next week

**Comment by elf-pavlik** [comment]
Awesome! I've created a shared pad, which includes a doodle pool for next Tuesday (July 4th) and a link to the usual notifications video conferencing room: https://hackmd.io/@solid/BJdbKRpOh

I'm going to start adding some topics which we could discuss. Please don't hesitate to add your notes and ideas.
I'm also going to play with this repo over this weekend to understand it better. Hope you see you both on Tuesday!

**Comment by elf-pavlik** [comment]
Thank you both for filling out the poll, based on it I selected tomorrow 14:00 UTC which is the most common time for most Solid meetings. I also reflected it on the pad :point_up: See you tomorrow!
